// =========================================================================
// src/providers/google.ts
// Handles Google OAuth 2.0 + OIDC authorization and token exchange.
// Uses PKCE (S256) — the code_verifier is generated by the session middleware
// and stored in KV alongside the state nonce.
// =========================================================================

// =========================================================================
// Imports
// =========================================================================
import { GoogleProfileSchema, type GoogleProfile } from '../schemas/index.js'

// =========================================================================
// Constants
// =========================================================================
const GOOGLE_AUTH_URL  = 'https://accounts.google.com/o/oauth2/v2/auth'
const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token'
const GOOGLE_SCOPES    = 'openid email profile'

// =========================================================================
// Types
// =========================================================================
interface GoogleTokenResponse {
  access_token:  string
  id_token:      string
  token_type:    string
  expires_in:    number
}

// =========================================================================
// Helpers
// =========================================================================

/**
 * Builds the Google authorization redirect URL with PKCE challenge.
 * @param clientId      - Google OAuth client ID from env.
 * @param redirectUri   - Registered callback URL.
 * @param state         - CSRF nonce stored in KV before redirect.
 * @param codeChallenge - PKCE S256 challenge derived from code_verifier.
 * @returns The full Google authorization URL.
 */
export function buildAuthUrl(
  clientId:      string,
  redirectUri:   string,
  state:         string,
  codeChallenge: string,
): string {
  const params = new URLSearchParams({
    client_id:             clientId,
    redirect_uri:          redirectUri,
    response_type:         'code',
    scope:                 GOOGLE_SCOPES,
    state,
    code_challenge:        codeChallenge,
    code_challenge_method: 'S256',
    // Always show the account picker — better UX for educational demo
    prompt:                'select_account',
  })
  return `${GOOGLE_AUTH_URL}?${params.toString()}`
}

/**
 * Decodes the payload segment of a JWT without verifying the signature.
 * Sufficient for extracting the id_token claims from Google since we
 * obtained the token directly via TLS from Google's token endpoint.
 *
 * @param jwt - The raw JWT string (three dot-separated base64url segments).
 * @returns The decoded payload as a plain object.
 */
function decodeIdToken(jwt: string): Record<string, unknown> {
  // JWT has three segments: header.payload.signature
  const [, payloadB64] = jwt.split('.')
  if (!payloadB64) throw new Error('Invalid id_token: missing payload segment')

  // Convert base64url → base64 → binary string → JSON
  const padded = payloadB64.replace(/-/g, '+').replace(/_/g, '/')
  const json   = atob(padded)
  return JSON.parse(json) as Record<string, unknown>
}

// =========================================================================
// Exports
// =========================================================================

/**
 * Exchanges the authorization code for tokens and returns the validated
 * Google profile extracted from the id_token payload.
 *
 * @param clientId     - Google OAuth client ID.
 * @param clientSecret - Google OAuth client secret.
 * @param code         - Authorization code from callback query params.
 * @param redirectUri  - Must match the one used in buildAuthUrl.
 * @param codeVerifier - PKCE verifier that was stored alongside the state.
 * @returns A Zod-validated `GoogleProfile` object.
 */
export async function exchangeCode(
  clientId:     string,
  clientSecret: string,
  code:         string,
  redirectUri:  string,
  codeVerifier: string,
): Promise<GoogleProfile> {
  const res = await fetch(GOOGLE_TOKEN_URL, {
    method:  'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id:     clientId,
      client_secret: clientSecret,
      code,
      redirect_uri:  redirectUri,
      grant_type:    'authorization_code',
      code_verifier: codeVerifier,
    }),
  })

  const tokens = await res.json() as GoogleTokenResponse
  if (!tokens.id_token) {
    throw new Error('Google token exchange failed: no id_token in response')
  }

  // Decode the id_token payload — validate shape with Zod
  const payload = decodeIdToken(tokens.id_token)
  return GoogleProfileSchema.parse(payload)
}
