// =========================================================================
// src/index.ts
// Hono application entry point.
// Registers all routes: static UI, OAuth redirect/callback for 5 providers,
// session resolution (/me), profile update (PATCH /me), and logout.
// =========================================================================

// =========================================================================
// Imports
// =========================================================================
import { Hono } from 'hono'
import { getCookie, setCookie, deleteCookie } from 'hono/cookie'
import { UpdateProfileSchema } from './schemas/index.js'
import { generateState, consumeState, generateCodeVerifier, generateCodeChallenge, sessionCookieName } from './middleware/session.js'
import { upsertUser, createSession, getSessionUser, updateProfile, deleteSession } from './db/users.js'
import * as GitHub from './providers/github.js'
import * as Google from './providers/google.js'
import * as Discord from './providers/discord.js'
import * as Steam from './providers/steam.js'
import * as Twitter from './providers/twitter.js'

// =========================================================================
// Constants
// =========================================================================
const COOKIE_MAX_AGE = 2_592_000   // 30 days (seconds)
const COOKIE_NAME = sessionCookieName()

// =========================================================================
// Types
// =========================================================================
type Bindings = Env  // generated by wrangler types

// =========================================================================
// App
// =========================================================================
const app = new Hono<{ Bindings: Bindings }>()

// =========================================================================
// GET / — Login page (served from public/ via wrangler Assets binding)
// =========================================================================
app.get('/', async (c) => {
  // Check if the user already has a valid session — redirect to /me if so
  const sessionId = getCookie(c, COOKIE_NAME)
  if (sessionId) {
    const user = await getSessionUser(c.env.DB, sessionId)
    if (user) return c.redirect('/me')
  }
  // Serve the static login page from the Assets binding
  return c.env.ASSETS.fetch(c.req.raw)
})

// =========================================================================
// GET /auth/:provider — Build provider authorization URL and redirect
// =========================================================================
app.get('/auth/:provider', async (c) => {
  const provider = c.req.param('provider')
  const baseUrl = c.env.BASE_URL
  const redirectUri = `${baseUrl}/callback/${provider}`

  let authUrl: string

  if (provider === 'github') {
    const state = await generateState(c.env.OAUTH_STATE, 'github')
    authUrl = GitHub.buildAuthUrl(c.env.GITHUB_CLIENT_ID, redirectUri, state)

  } else if (provider === 'google') {
    const verifier = generateCodeVerifier()
    const challenge = await generateCodeChallenge(verifier)
    const state = await generateState(c.env.OAUTH_STATE, 'google', verifier)
    authUrl = Google.buildAuthUrl(c.env.GOOGLE_CLIENT_ID, redirectUri, state, challenge)

  } else if (provider === 'discord') {
    const state = await generateState(c.env.OAUTH_STATE, 'discord')
    authUrl = Discord.buildAuthUrl(c.env.DISCORD_CLIENT_ID, redirectUri, state)

  } else if (provider === 'steam') {
    // Steam uses OpenID 2.0 — state is embedded in the return_to URL
    const state = await generateState(c.env.OAUTH_STATE, 'steam')
    const returnUrl = `${redirectUri}?state=${state}`
    authUrl = Steam.buildAuthUrl(returnUrl)

  } else if (provider === 'twitter') {
    const verifier = generateCodeVerifier()
    const challenge = await generateCodeChallenge(verifier)
    const state = await generateState(c.env.OAUTH_STATE, 'twitter', verifier)
    authUrl = Twitter.buildAuthUrl(c.env.TWITTER_CLIENT_ID, redirectUri, state, challenge)

  } else {
    return c.json({ error: 'unknown_provider' }, 400)
  }

  return c.redirect(authUrl)
})

// =========================================================================
// GET /callback/:provider — Verify state, exchange code, upsert user, set cookie
// =========================================================================
app.get('/callback/:provider', async (c) => {
  const provider = c.req.param('provider')
  const query = c.req.query()

  // ── CSRF: validate state before doing anything with the code ──────────
  const state = query['state'] ?? ''
  const stored = await consumeState(c.env.OAUTH_STATE, state)
  if (!stored || stored.provider !== provider) {
    return c.json({ error: 'invalid_state' }, 400)
  }

  const baseUrl = c.env.BASE_URL
  const redirectUri = `${baseUrl}/callback/${provider}`
  const code = query['code'] ?? ''
  const userAgent = c.req.header('User-Agent') ?? null
  const ip = c.req.header('CF-Connecting-IP') ?? null

  try {
    let userId: string

    if (provider === 'github') {
      const token = await GitHub.exchangeCode(
        c.env.GITHUB_CLIENT_ID, c.env.GITHUB_CLIENT_SECRET, code, redirectUri,
      )
      const profile = await GitHub.fetchProfile(token)
      userId = await upsertUser(c.env.DB, 'github', {
        providerSub: String(profile.id),
        providerDisplayName: profile.name ?? profile.login,
        avatarUrl: profile.avatar_url,
        email: profile.email,
      })

    } else if (provider === 'google') {
      const profile = await Google.exchangeCode(
        c.env.GOOGLE_CLIENT_ID, c.env.GOOGLE_CLIENT_SECRET,
        code, redirectUri, stored.code_verifier ?? '',
      )
      userId = await upsertUser(c.env.DB, 'google', {
        providerSub: profile.sub,
        providerDisplayName: profile.name,
        avatarUrl: profile.picture,
        email: profile.email,
      })

    } else if (provider === 'discord') {
      const token = await Discord.exchangeCode(
        c.env.DISCORD_CLIENT_ID, c.env.DISCORD_CLIENT_SECRET, code, redirectUri,
      )
      const profile = await Discord.fetchProfile(token)
      const avatar = Discord.buildAvatarUrl(profile.id, profile.avatar)
      userId = await upsertUser(c.env.DB, 'discord', {
        providerSub: profile.id,
        providerDisplayName: profile.username,
        avatarUrl: avatar,
        email: profile.email ?? null,
      })

    } else if (provider === 'steam') {
      // Steam: verify the OpenID assertion, then fetch avatar
      const params = new URLSearchParams(query)
      const steamId = await Steam.verifySteamCallback(params)
      const player = await Steam.fetchPlayerSummary(steamId, c.env.STEAM_API_KEY)
      userId = await upsertUser(c.env.DB, 'steam', {
        providerSub: player.steamid,
        providerDisplayName: player.personaname,
        avatarUrl: player.avatarfull,
        email: null,
      })

    } else if (provider === 'twitter') {
      const token = await Twitter.exchangeCode(
        c.env.TWITTER_CLIENT_ID, c.env.TWITTER_CLIENT_SECRET,
        code, redirectUri, stored.code_verifier ?? '',
      )
      const profile = await Twitter.fetchProfile(token)
      userId = await upsertUser(c.env.DB, 'twitter', {
        providerSub: profile.data.id,
        providerDisplayName: profile.data.name,
        avatarUrl: profile.data.profile_image_url ?? null,
        email: null,
      })

    } else {
      return c.json({ error: 'unknown_provider' }, 400)
    }

    // Create D1 session and set the HttpOnly cookie
    const sessionId = await createSession(c.env.DB, userId, provider, userAgent, ip)
    setCookie(c, COOKIE_NAME, sessionId, {
      httpOnly: true,
      secure: true,
      sameSite: 'Lax',
      maxAge: COOKIE_MAX_AGE,
      path: '/',
    })

    return c.redirect('/')

  } catch (err) {
    console.error(`[callback/${provider}] error:`, err)
    return c.json({ error: 'callback_failed', detail: String(err) }, 500)
  }
})

// =========================================================================
// GET /me — Return current session user as JSON
// =========================================================================
app.get('/me', async (c) => {
  const sessionId = getCookie(c, COOKIE_NAME)
  if (!sessionId) return c.json({ error: 'unauthorized' }, 401)

  const user = await getSessionUser(c.env.DB, sessionId)
  if (!user) return c.json({ error: 'unauthorized' }, 401)

  return c.json({
    id: user.id,
    username: user.username,
    display_name: user.display_name,
    avatar_url: user.avatar_url,
    email: user.email,
    provider: user.provider,
  })
})

// =========================================================================
// PATCH /me — Update display_name and/or username
// =========================================================================
app.patch('/me', async (c) => {
  const sessionId = getCookie(c, COOKIE_NAME)
  if (!sessionId) return c.json({ error: 'unauthorized' }, 401)

  const user = await getSessionUser(c.env.DB, sessionId)
  if (!user) return c.json({ error: 'unauthorized' }, 401)

  // Validate request body at the trust boundary
  const body = await c.req.json().catch(() => null)
  const parsed = UpdateProfileSchema.safeParse(body)
  if (!parsed.success) {
    return c.json({ error: 'invalid_body', issues: parsed.error.issues }, 400)
  }

  const result = await updateProfile(
    c.env.DB,
    user.id,
    parsed.data.display_name,
    parsed.data.username,
  )

  if (result === 'username_taken') {
    return c.json({ error: 'username_taken' }, 409)
  }

  return c.json({ ok: true })
})

// =========================================================================
// GET /logout — Invalidate session in D1 and clear cookie
// =========================================================================
app.get('/logout', async (c) => {
  const sessionId = getCookie(c, COOKIE_NAME)
  if (sessionId) {
    await deleteSession(c.env.DB, sessionId)
  }
  // Clear the cookie regardless of whether a session existed
  deleteCookie(c, COOKIE_NAME, { path: '/' })
  return c.redirect('/')
})

// =========================================================================
// Exports
// =========================================================================
export default app
